webtalk_init -webtalk_dir /home/tobias/Development/TURBOdeb/repar_turing_bombe/turing_bombe_project/vivado/TURBO.sim/sim_1/behav/xsim/xsim.dir/turing_bombe_wrapper_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jun 13 21:27:29 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9f012e4b-1f72-429c-b710-2d1f06835b34" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c627cf18f339459286b6ed0a75ed9fea" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1991.854 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "125972_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3579226922 -regid "" -xml /home/tobias/Development/TURBOdeb/repar_turing_bombe/turing_bombe_project/vivado/TURBO.sim/sim_1/behav/xsim/xsim.dir/turing_bombe_wrapper_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/tobias/Development/TURBOdeb/repar_turing_bombe/turing_bombe_project/vivado/TURBO.sim/sim_1/behav/xsim/xsim.dir/turing_bombe_wrapper_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/tobias/Development/TURBOdeb/repar_turing_bombe/turing_bombe_project/vivado/TURBO.sim/sim_1/behav/xsim/xsim.dir/turing_bombe_wrapper_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
