webtalk_init -webtalk_dir /home/tobias/Development/TURBOdeb/repar_turing_bombe/turing_bombe_project/vivado/TURBO.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-10-09 15:39:32" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6m79da8abvn11erbvkauue811d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1773.902 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8,276 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1570628121000" -context "sdk\\\\bsp/1570628121000"
webtalk_add_data -client sdk -key hwid -value "1570595233000" -context "sdk\\\\bsp/1570628121000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1570628121000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1570628121000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1570628121000"
webtalk_add_data -client sdk -key uid -value "1570628122000" -context "sdk\\\\application/1570628122000"
webtalk_add_data -client sdk -key hwid -value "1570595233000" -context "sdk\\\\application/1570628122000"
webtalk_add_data -client sdk -key bspid -value "1570628121000" -context "sdk\\\\application/1570628122000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1570628122000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1570628122000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1570628122000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1570628122000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1570628122000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1570628122000"
webtalk_add_data -client sdk -key projSize -value "190.1953125" -context "sdk\\\\application/1570628122000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1570628372012"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1570628372012"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1570628372012"
webtalk_add_data -client sdk -key DebugCount -value "1" -context "sdk\\\\bsp/1570628372012"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1570628372012"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1570628372012"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1570628372012"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1570628372012"
webtalk_transmit -clientid 1772272740 -regid "" -xml /home/tobias/Development/TURBOdeb/repar_turing_bombe/turing_bombe_project/vivado/TURBO.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/tobias/Development/TURBOdeb/repar_turing_bombe/turing_bombe_project/vivado/TURBO.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/tobias/Development/TURBOdeb/repar_turing_bombe/turing_bombe_project/vivado/TURBO.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
