# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /homes/mexner/TURBOdeb/turing_bombe_project/src/xdc/Zybo-Z7-Master.xdc

# Block Designs: /homes/mexner/TURBOdeb/turing_bombe_project/src/bd/turing_bombe/turing_bombe.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==turing_bombe || ORIG_REF_NAME==turing_bombe} -quiet] -quiet

# IP: /homes/mexner/TURBOdeb/turing_bombe_project/src/bd/turing_bombe/ip/turing_bombe_indicator_drum_0_0/turing_bombe_indicator_drum_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==turing_bombe_indicator_drum_0_0 || ORIG_REF_NAME==turing_bombe_indicator_drum_0_0} -quiet] -quiet

# IP: /homes/mexner/TURBOdeb/turing_bombe_project/src/bd/turing_bombe/ip/turing_bombe_turing_bombe_control_0_0/turing_bombe_turing_bombe_control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==turing_bombe_turing_bombe_control_0_0 || ORIG_REF_NAME==turing_bombe_turing_bombe_control_0_0} -quiet] -quiet

# IP: /homes/mexner/TURBOdeb/turing_bombe_project/src/bd/turing_bombe/ip/turing_bombe_diagonal_board_0_0/turing_bombe_diagonal_board_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==turing_bombe_diagonal_board_0_0 || ORIG_REF_NAME==turing_bombe_diagonal_board_0_0} -quiet] -quiet

# Block Designs: /homes/mexner/TURBOdeb/turing_bombe_project/src/bd/design_enigma/design_enigma.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_enigma || ORIG_REF_NAME==design_enigma} -quiet] -quiet

# IP: /homes/mexner/TURBOdeb/turing_bombe_project/src/bd/design_enigma/ip/design_enigma_pseudo_lut_0_0/design_enigma_pseudo_lut_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_enigma_pseudo_lut_0_0 || ORIG_REF_NAME==design_enigma_pseudo_lut_0_0} -quiet] -quiet

# IP: /homes/mexner/TURBOdeb/turing_bombe_project/src/bd/design_enigma/ip/design_enigma_drum_0_0/design_enigma_drum_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_enigma_drum_0_0 || ORIG_REF_NAME==design_enigma_drum_0_0} -quiet] -quiet

# IP: /homes/mexner/TURBOdeb/turing_bombe_project/src/bd/design_enigma/ip/design_enigma_drum_1_0/design_enigma_drum_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_enigma_drum_1_0 || ORIG_REF_NAME==design_enigma_drum_1_0} -quiet] -quiet

# IP: /homes/mexner/TURBOdeb/turing_bombe_project/src/bd/design_enigma/ip/design_enigma_drum_2_0/design_enigma_drum_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_enigma_drum_2_0 || ORIG_REF_NAME==design_enigma_drum_2_0} -quiet] -quiet

# IP: /homes/mexner/TURBOdeb/turing_bombe_project/src/bd/design_enigma/ip/design_enigma_drum_ukw_0_0/design_enigma_drum_ukw_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_enigma_drum_ukw_0_0 || ORIG_REF_NAME==design_enigma_drum_ukw_0_0} -quiet] -quiet

# IP: /homes/mexner/TURBOdeb/turing_bombe_project/src/bd/design_enigma/ip/design_enigma_enigma_control_0_0/design_enigma_enigma_control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_enigma_enigma_control_0_0 || ORIG_REF_NAME==design_enigma_enigma_control_0_0} -quiet] -quiet

# IP: /homes/mexner/TURBOdeb/turing_bombe_project/src/bd/design_enigma/ip/design_enigma_xlconstant_0_0/design_enigma_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_enigma_xlconstant_0_0 || ORIG_REF_NAME==design_enigma_xlconstant_0_0} -quiet] -quiet

# XDC: /homes/mexner/TURBOdeb/turing_bombe_project/src/bd/turing_bombe/turing_bombe_ooc.xdc

# XDC: /homes/mexner/TURBOdeb/turing_bombe_project/src/bd/design_enigma/design_enigma_ooc.xdc
