webtalk_init -webtalk_dir /homes/mexner/TURBOdeb/turing_bombe_project/xsdk/workspace/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-10-28 16:12:46" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210753198_202014026_210680099_023" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2ao4dlkvunkqchap6gmu4uvk1m" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4459.527 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16,683 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1572274878000" -context "sdk\\\\bsp/1572274878000"
webtalk_add_data -client sdk -key hwid -value "1572272413000" -context "sdk\\\\bsp/1572274878000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1572274878000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1572274878000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1572274878000"
webtalk_add_data -client sdk -key uid -value "1572274890000" -context "sdk\\\\application/1572274890000"
webtalk_add_data -client sdk -key hwid -value "1572272413000" -context "sdk\\\\application/1572274890000"
webtalk_add_data -client sdk -key bspid -value "1572274878000" -context "sdk\\\\application/1572274890000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1572274890000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1572274890000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1572274890000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1572274890000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1572274890000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1572274890000"
webtalk_add_data -client sdk -key projSize -value "312.125" -context "sdk\\\\application/1572274890000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1572275566583"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1572275566583"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1572275566583"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1572275566583"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1572275566583"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1572275566583"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1572275566583"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1572275566583"
webtalk_transmit -clientid 1926828683 -regid "210753198_202014026_210680099_023" -xml /homes/mexner/TURBOdeb/turing_bombe_project/xsdk/workspace/webtalk/usage_statistics_ext_sdk.xml -html /homes/mexner/TURBOdeb/turing_bombe_project/xsdk/workspace/webtalk/usage_statistics_ext_sdk.html -wdm /homes/mexner/TURBOdeb/turing_bombe_project/xsdk/workspace/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
