webtalk_init -webtalk_dir /home/tobias/Development/TURBOdeb/turing_bombe_project/xsdk/workspace/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-11-04 18:12:59" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "up6es78hlftdgihsng8eg8u2je" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_20" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "20" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1980.941 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8,276 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1572887543000" -context "sdk\\\\hardware/1572887543000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1572887543000"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1572887543000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1572887543000"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.3" -context "sdk\\\\hardware/1572887543000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1572887543000"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1572887543000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1572887543000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1572887543000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1572887543000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1572887543000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1572887579781"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1572887579781"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1572887579781"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1572887579781"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1572887579781"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1572887579781"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1572887579781"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1572887579781"
webtalk_transmit -clientid 2169933662 -regid "" -xml /home/tobias/Development/TURBOdeb/turing_bombe_project/xsdk/workspace/webtalk/usage_statistics_ext_sdk.xml -html /home/tobias/Development/TURBOdeb/turing_bombe_project/xsdk/workspace/webtalk/usage_statistics_ext_sdk.html -wdm /home/tobias/Development/TURBOdeb/turing_bombe_project/xsdk/workspace/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
